language: csharp
dist: trusty
mono: none
dotnet: 2.1.300
os:
- linux
script:
- if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
#- if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
- dotnet build -c Release
- if test "$TRAVIS_OS_NAME" == "linux"; then dotnet test -c Release ./tests/Emuses.Tests/Emuses.Tests.csproj; fi