environment:
  CLI_VERSION: 1.0.4

#install:
  #- ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  #- ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  #- ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
  #- ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR'
  #- ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

#build_script:
  # dotnet info
  #- ps: dotnet --info
  # Run dotnet new 
  #- ps: mkdir "test\test-dotnet-new" -Force | Push-Location
  #- ps: dotnet new console -lang f#
  #- ps: dotnet restore
  #- ps: dotnet build
  #- ps: dotnet run a b
  #- ps: Pop-Location

version: 1.0.{build}
image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: dotnet --info
#- cmd: >-
#    dotnet restore
#    dotnet build -c Release
#test_script:
#- cmd: dotnet test -c Release ./tests/Emuses.Tests/Emuses.Tests.csproj